# Generated by Django 2.1.2 on 2018-12-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0025_auto_20181208_1717'),
        ('users', '0002_profile_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='addresses',
            field=models.ManyToManyField(to='items.Address'),
        ),
    ]
