# Generated by Django 2.1.2 on 2018-12-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deliver_time',
            field=models.DateTimeField(default=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_time',
            field=models.DateTimeField(default=''),
        ),
    ]
