# Generated by Django 2.1.2 on 2018-12-02 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_auto_20181202_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deliver_time',
            field=models.DateTimeField(default=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_time',
            field=models.DateTimeField(default=''),
        ),
    ]
