# Generated by Django 2.1.2 on 2018-12-06 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_order_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toppings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('category_description', models.TextField(blank=True, max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_delivered',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='is_ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='ref_code',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='toppings',
            field=models.ManyToManyField(blank=True, to='items.Toppings'),
        ),
    ]
