# Generated by Django 2.1.2 on 2018-12-07 00:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_auto_20181206_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deliver_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
