# Generated by Django 2.1.2 on 2018-12-07 00:40

from django.db import migrations


class Migration(migrations.Migration):
    atomic=False

    dependencies = [
        ('items', '0014_auto_20181207_0039'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Toppings',
            new_name='Topping',
        ),
    ]
