# Generated by Django 2.1.2 on 2018-12-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0017_auto_20181207_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='selcted',
            field=models.BooleanField(default=False),
        ),
    ]
