# Generated by Django 2.1.2 on 2018-12-08 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0019_remove_menuitem_selcted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('appartment_number', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_type',
            new_name='type',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='items.Address'),
        ),
    ]
