# Generated by Django 2.1.2 on 2018-12-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_orders'),
        ('items', '0023_auto_20181208_0408'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='customers',
            field=models.ManyToManyField(to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='address',
            name='appartment_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ManyToManyField(default='', null=True, to='items.Address'),
        ),
    ]
