# Generated by Django 2.1.2 on 2018-12-08 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0024_auto_20181208_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='items.Address'),
        ),
    ]
