# Generated by Django 2.1.2 on 2018-12-08 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0027_auto_20181208_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.MenuItem')),
            ],
        ),
    ]
