# Generated by Django 2.1.2 on 2018-12-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0033_orderitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topping',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
