# Generated by Django 2.1.2 on 2018-12-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0034_auto_20181225_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ToppingsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount_allowed', models.PositiveIntegerField(blank=True)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
    ]
