# Generated by Django 2.1.2 on 2018-12-25 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0038_auto_20181225_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='toppingscategory',
            name='description',
            field=models.TextField(blank=True, default='', max_length=100, null=True),
        ),
    ]
