# Generated by Django 2.1.2 on 2018-12-25 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0039_toppingscategory_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topping',
            name='category_description',
        ),
        migrations.AlterField(
            model_name='topping',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='items.ToppingsCategory'),
        ),
    ]
