# Generated by Django 2.1.2 on 2018-12-27 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0040_auto_20181225_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(max_length=22),
        ),
    ]
