# Generated by Django 2.1.2 on 2018-12-27 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0041_auto_20181227_0334'),
    ]

    operations = [
        migrations.AddField(
            model_name='toppingscategory',
            name='required',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
