# Generated by Django 2.1.2 on 2018-12-29 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0044_menuitem_helos'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='menu_item_pics'),
        ),
    ]
