# Generated by Django 2.1.2 on 2018-12-29 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0045_menuitem_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='helos',
        ),
    ]
